import Link from "next/link";
//import file globals,css
import "./globals.css";
import Image from "next/image";
//import font awesome
import "@fortawesome/fontawesome-svg-core/styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* area header*/}
        <header>
          {/* area iamge/banner */}
          {/* <img src="../images/logo.png" alt="Logo UTI"/> */}
          <Image
            src={"/images/logo.png"}
            alt="Logo UTI"
            width={320}
            height={60}
          ></Image>

          {/* area menu */}
          <nav className="mt-5 flex justify-center text-center">
            <Link
              href={"/"}
              className="bg-blue-800 hover:bg-blue-950 text-white rounded-full px-5 py-2.5 mr-3 w-52 "
            >
              Data Mahasiswa
            </Link>
            <Link
              href={"/"}
              className="bg-blue-800 hover:bg-blue-950 text-white rounded-full px-5 py-2.5 ml-3 w-52 "
            >
              Log Data Mahasiswa
            </Link>
          </nav>
        </header>

        {/*area content*/}
        <section className="m-5">{children}</section>
        {/* area footer */}
        <footer className=" flex justify-center bg-color1 text-color3-1 py-15X">
          Copyright &copy; 2024 - Tias Haikal Mulyana . com
        </footer>
      </body>
    </html>
  );
}
